name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Get version from tag (v1.0.0 → 1.0.0)
      - name: Get version from tag
        id: get_version
        run: |
          $tag = "${{ github.ref_name }}"
          $ver = $tag.TrimStart("v")
          echo "version=$ver" >> $env:GITHUB_OUTPUT

      # Update project version in csproj
      - name: Update project version from tag
        run: |
          $version = "${{ steps.get_version.outputs.version }}"
          (Get-Content ITQuestions/ITQuestions.csproj) `
          -replace '<Version>.*</Version>', "<Version>$version</Version>" `
          -replace '<AssemblyVersion>.*</AssemblyVersion>', "<AssemblyVersion>$version</AssemblyVersion>" `
          -replace '<FileVersion>.*</FileVersion>', "<FileVersion>$version</FileVersion>" `
          | Set-Content ITQuestions/ITQuestions.csproj

      # Setup .NET
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Build
      - name: Publish self-contained app
        run: dotnet publish ITQuestions/ITQuestions.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true /p:PublishTrimmed=false -o publish

      - name: List publish output
        run: dir publish

      # Install Inno Setup (adds iscc.exe to PATH)
      - name: Setup Inno Setup
        uses: Minionguyjpro/Inno-Setup-Action@v1.1.0

      # Build installer from .iss script
      - name: Build installer
        run: iscc /dMyAppVersion=${{ steps.get_version.outputs.version }} Installer\ITQuestionsInstaller.iss
        
      # Get last commit message → changelog
      - name: Get last commit message
        id: last_commit
        shell: pwsh
        run: |
          $msg = git log -1 --pretty=%B
          echo "message=$msg" >> $env:GITHUB_OUTPUT

      # Generate update.json
      - name: Generate update.json
        shell: pwsh
        run: |
          $ver  = '${{ steps.get_version.outputs.version }}'
          $repo = '${{ github.repository }}'

          # Preserve multiline commit message
          $raw  = @'
          ${{ toJson(steps.last_commit.outputs.message) }}
          '@
          $msg  = $raw | ConvertFrom-Json

          if (-not $msg) { $msg = "Release v$ver" }

          $obj = [ordered]@{
            LatestVersion = $ver
            DownloadUrl   = "https://github.com/$repo/releases/download/v$ver/ITQuestions.exe"
            Changelog     = $msg
          }
          $obj | ConvertTo-Json -Depth 5 | Out-File -FilePath update.json -Encoding utf8

      # Upload to Release
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            publish/ITQuestions.exe
            update.json
            Installer/Output/ITQuestionsSetup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
