name: Build and Release

on:
  push:
    tags:
      - 'v*'   # Runs only when you push a tag like v1.1.0

permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish self-contained app
        run: dotnet publish ITQuestions/ITQuestions.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true /p:PublishTrimmed=false -o publish

      - name: List publish output
        run: dir publish

      - name: Create zip
        run: powershell Compress-Archive -Path publish/* -DestinationPath ITQuestions-${{ github.ref_name }}.zip

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ITQuestions-${{ github.ref_name }}.zip
            publish/ITQuestions.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
